---
- name: Aktualizacja backendu
  hosts: vps
  remote_user: debian
  become: true
  any_errors_fatal: true

  pre_tasks:
    - name: "Check if destination distribution is debian"
      ansible.builtin.debug:
        msg: "Jeżeli dystrybucja docelowa, to nie Debian, nic nie zostanie wykonane"
      failed_when: ansible_facts['os_family'] != "Debian"
      when: ansible_facts['os_family'] != "Debian"

  vars:
    v:
      - type: "{{ lookup('ansible.builtin.env', 'type') }}"
        repo: "{{ lookup('ansible.builtin.env', 'repo') }}"
        files: ["wwwroot", "logs"]
        state:: ["absent", "directory"]

  tasks:
    - name: Stop pooposting
      ansible.builtin.service:
        name: "pooposting-api-{{ item.type }}"
        enabled: true
        state: stopped
      with_items:
        - "{{ v }}"
    - name: Zaciągnięcie zmian do repo
      ansible.builtin.git:
        repo: 'https://github.com/PooPosting/Back-end.git'
        single_branch: true
        update: true
        dest: "/home/debian/pooposting-backend-{{ item.type }}/api"
        version: "{{ item.repo }}"
      with_items:
        - "{{ v }}"
    - name: Aktualizacja pliku appsettings
      ansible.builtin.template:
        src: "appsettings.json"
        dest: "/home/debian/pooposting-backend-{{ item.type }}/PooPosting.Api/appsettings.json"
        owner: root
        group: root
        mode: 0400
        force: true
      with_items:
        - "{{ v }}"
    - name: Wykonanie dotnet ef db update
      ansible.builtin.shell:
        chdir: "/home/debian/pooposting-backend-{{ item.type }}"
        cmd: "export PATH=\"$PATH:$HOME/.dotnet/tools\" && dotnet ef database update --project PooPosting.Domain/PooPosting.Domain.csproj \
          --startup-project PooPosting.Api/PooPosting.Api.csproj --context PooPosting.Domain.DbContext.PictureDbContext"
      changed_when: true
      with_items:
        - "{{ v }}"
    - name: Przeniesieie plików do /tmp
      ansible.builtin.copy:
        remote_src: true
        src: "/var/www/pooposting-{{ item.0.type }}/api/{{ item.1 }}"
        dest: "/tmp"
        owner: root
        group: root
        mode: 0755
      with_nested:
        - "{{ v }}"
        - ['wwwroot', 'api']
    - name: Kasowanie zawartości katalogu
      ansible.builtin.file:
        state: "{{ item.state }}"
        path: "/var/www/pooposting-{{ item.type }}/api"
        owner: www-data
        group: www-data
        mode: 0755
      with_subelements:
        - "{{ v }}"
    - name: Wykonanie dotnet punlish
      ansible.builtin.command:
        chdir: "/home/debian/pooposting-backend-{{ item.type }}/PooPosting.Api"
        cmd: "dotnet publish --configuration Release --output /var/www/pooposting-{{ item.type }}/api"
      changed_when: true
    - name: Przeniesienie z powrotem plików
      ansible.builtin.copy:
        owner: root
        group: root
        mode: 0755
        src: "/tmp/{{ item.files }}"
        dest: "/var/www/pooposting-{{ item.type }}/api"
      with_items:
        - "{{ v }}"
    - name: Kasowanie plików z tmp
      ansible.builtin.file:
        state: absent
        path: "/tmp/{{ item.files }}"
    - name: Start pooposting
      ansible.builtin.service:
        name: "pooposting-api-{{ item.type }}"
        enabled: true
        state: started
...
