---
- name: Uruchomienie nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  listen: "Start LEM"
- name: Uruchomienie serwera mysql
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  listen: "Start LEM"
- name: Start PHP
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
- name: Restart f2b
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
- name: Enable pooposting prod
  ansible.builtin.service:
    name: "pooposting-api-prod"
    daemon_reload: true
    state: started
    enabled: true
  listen: Enable pooposting
- name: Enable pooposting dev
  ansible.builtin.service:
    name: "pooposting-api-dev"
    daemon_reload: true
    state: started
    enabled: true
  listen: Enable pooposting
- name: Restart pooposting prod
  ansible.builtin.service:
    name: "pooposting-api-prod"
    state: restarted
    enabled: true
  listen: Restart pooposting
- name: Restart pooposting dev
  ansible.builtin.service:
    name: "pooposting-api-dev"
    state: restarted
    enabled: true
  listen: Restart pooposting
...
