---
- name: Uruchomienie nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  listen: "Start LEM"
- name: Uruchomienie serwera mysql
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  listen: "Start LEM"
- name: Start PHP
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
- name: Restart f2b
  ansible.builtin.service:
    name: fail2ban
    state: restarted
    enabled: true
...
