---
- name: Instalacja nginx i mariadb
  ansible.builtin.apt:
    update_cache: true
    name:
      - nginx-full
      - mariadb-server
      - mariadb-client
      - python3-mysqldb
  notify: "Start LEM"
- name: Przeniesienie skryptu na zdalną maszynę
  ansible.builtin.copy:
    src: ips.sh
    dest: /tmp/ips.sh
    mode: 0740
    owner: root
    group: root
- name: Konfiguracja nginx realip
  ansible.builtin.script: ips.sh
  args:
    chdir: /tmp
  notify: Restart nginx
- name: Zezwolenie na ruch HTTP i HTTPS
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items:
    - 80
    - 443
- name: Zapis iptables-persistent
  community.general.iptables_state:
    state: saved
    ip_version: "{{ item.version }}"
    path: "/etc/iptables/rules.{{ item.name }}"
  with_items:
    - { version: 'ipv4', name: 'v4' }
    - { version: 'ipv6', name: 'v6' }
- name: Konfiguracja użytkownika (administracyjnego) bazy danych
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    priv: "*.*:ALL"
    state: present
  with_items: "{{ db_users }}"
- name: Instalacja repozytoriów serwera DOTNet
  ansible.builtin.apt:
    deb: "https://packages.microsoft.com/config/debian/{{ ansible_distribution_major_version }}/packages-microsoft-prod.deb"
    state: present
- name: Instalacja zależności
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - "dotnet-sdk-{{ d_version }}"
      - "aspnetcore-runtime-{{ d_version }}"
      - git
    state: present
- name: Instalacja nodejs
  block:
    - name: Instalacja zależności
      ansible.builtin.apt:
        update_cache: true
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg
    - name: Dodanie klucza GPG nodejs
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        state: present
        keyring: /etc/apt/keyrings/nodesource.gpg
    - name: Dodanie repo Nodejs
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_18.x nodistro main"
    - name: Instalacja nodejs
      ansible.builtin.apt:
        update_cache: true
        name: nodejs
        state: present
- name: Instalacja angular npm
  community.general.npm:
    name: "@angular/cli"
    global: true
    state: present
- name: Instalacja PHP dla PHPMyAdmin
  block:
    - name: Dodanie klucza GPG PHP
      ansible.builtin.apt_key:
        url: https://packages.sury.org/php/apt.gpg
        state: present
        keyring: /usr/share/keyrings/deb.sury.org-php.gpg
    - name: Dodanie repo PHP
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_facts['distribution_release'] }} main
    - name: Instalacja modułów PHP
      ansible.builtin.apt:
        update_cache: true
        name:
          - php8.1-fpm
          - php8.1-mbstring
          - php8.1-bcmath
          - php8.1-xml
          - php8.1-mysql
          - php8.1-common
          - php8.1-gd
          - php8.1-cli
          - php8.1-curl
          - php8.1-zip
        state: present
      notify: Start PHP
- name: Instalacja unzip i tar
  ansible.builtin.apt:
    update_cache: true
    name:
      - tar
      - unzip
    state: present
- name: Pobranie PHPMyAdmin
  ansible.builtin.unarchive:
    dest: /var/www
    remote_src: true
    src: https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.zip
- name: Wrzucenie całości do odpowiedniego katalogu
  ansible.builtin.copy:
    src: /var/www/phpMyAdmin-5.2.1-all-languages/
    dest: /var/www/phpmyadmin
    mode: 0755
    owner: www-data
    group: www-data
    force: false
    remote_src: true
- name: Kasowanie pobranego archiwum
  ansible.builtin.file:
    state: absent
    path: /var/www/phpMyAdmin-5.2.1-all-languages
- name: Stworzenie pliku konfiguracyjnego
  ansible.builtin.copy:
    src: /var/www/phpmyadmin/config.sample.inc.php
    dest: /var/www/phpmyadmin/config.inc.php
    mode: 0644
    remote_src: true
    owner: www-data
    group: www-data
- name: Dodanie hasha do pliku konfiguracyjnego
  ansible.builtin.lineinfile:
    path: /var/www/phpmyadmin/config.inc.php
    regexp: "blowfish_secret"
    line: "$cfg['blowfish_secret'] = '{{ lookup('community.general.random_string') | password_hash(hashtype='blowfish') }}';"
- name: Konfiguracja nginx phpmyadmin
  notify: Restart nginx
  block:
    - name: Podrzucenie vhosta nginx dla phpmyadmin
      ansible.builtin.template:
        src: pma-nginx.j2
        dest: "/etc/nginx/sites-available/{{ pma_domain }}.conf"
        mode: 0640
        owner: root
        group: root
    - name: Uruchomienie konfiguracji nginx
      ansible.builtin.file:
        state: link
        src: "/etc/nginx/sites-available/{{ pma_domain }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ pma_domain }}.conf"
- name: Dodanie konfiguracji fail2ban do ochrony phpmyadmin
  ansible.builtin.blockinfile:
    state: present
    insertafter: EOF
    block: |
      [phpmyadmin-syslog]
      enabled = true
      filter = phpmyadmin-syslog
      logpath = /var/log/auth.log
    path: /etc/fail2ban/jail.local
    marker: ""
  notify: Restart f2b
- name: Stworzenie katalogów w /var/www
  ansible.builtin.file:
    path: "/var/www/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "pooposting-dev"
    - "pooposting-prod"
- name: Stworzenie katalogów w /home/debian
  ansible.builtin.file:
    path: "/home/debian/{{ item }}"
    state: directory
    mode: 0755
    owner: debian
    group: debian
  with_items:
    - "pooposting-frontend-prod"
    - "pooposting-frontend-dev"
    - "pooposting-backend-prod"
    - "pooposting-backend-dev"
- name: Pobranie zawartości repozytoriów do katalogów
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "/home/debian/{{ item.catalog }}"
    version: "{{ item.branch }}"
    single_branch: true
  with_items:
    - { repo: 'https://github.com/PooPosting/Front-end.git', catalog: 'pooposting-frontend-prod', branch: 'main' }
    - { repo: 'https://github.com/PooPosting/Front-end.git', catalog: 'pooposting-frontend-dev', branch: 'development' }
    - { repo: 'https://github.com/PooPosting/Back-end.git', catalog: 'pooposting-backend-prod', branch: 'main' }
    - { repo: 'https://github.com/PooPosting/Back-end.git', catalog: 'pooposting-backend-dev', branch: 'development' }
- name: Npm install w repo frontu
  community.general.npm:
    path: "/home/debian/pooposting-frontend-{{ item.type }}"
    state: present
  with_items:
    - "{{ db_users }}"
- name: Ng build
  ansible.builtin.command:
    chdir: "/home/debian/pooposting-frontend-{{ item.type }}"
    cmd: "ng build -c {{ item.type }}-server"
  changed_when: true
  with_items:
    - "{{ db_users }}"
- name: Skopiowanie plików na odpowiednie miejsca
  ansible.builtin.copy:
    src: "/home/debian/pooposting-frontend-{{ item.type }}/dist/"
    dest: "/var/www/pooposting-{{ item.type }}"
    owner: www-data
    group: www-data
    remote_src: true
    mode: 0755
  with_items:
    - "{{ db_users }}"
- name: Kasowanie katalogu dist
  ansible.builtin.file:
    state: absent
    path: "/home/debian/pooposting-frontend-{{ item.type }}/dist"
  with_items:
    - "{{ db_users }}"
- name: Wykonanie dotnet tool install
  ansible.builtin.command:
    cmd: "dotnet tool update --global dotnet-ef --version {{ d_version }}"
  changed_when: true
- name: Podrzucenie pliku appsettings
  ansible.builtin.template:
    src: appsettings.json.j2
    dest: "/home/debian/pooposting-backend-{{ item.type }}/PooPosting.Api/appsettings.json"
    owner: root
    group: root
    mode: 0400
  with_items:
    - "{{ db_users }}"
- name: Wykonanie dotnet ef db update
  ansible.builtin.shell:
    chdir: "/home/debian/pooposting-backend-{{ item.type }}/PooPosting.Api"
    cmd: "export PATH=\"$PATH:$HOME/.dotnet/tools\" && dotnet ef database update --project PooPosting.Domain\PooPosting.Domain.csproj \
          --startup-project PooPosting.Api\PooPosting.Api.csproj --context PooPosting.Domain.DbContext.PictureDbContext"
  changed_when: true
  with_items:
    - "{{ db_users }}"
- name: Podrzucenie konfiguracji systemd
  ansible.builtin.template:
    mode: 0640
    src: "systemd-poo-{{ item.type }}.j2"
    dest: "/etc/systemd/system/pooposting-api-{{ item.type }}.service"
    owner: root
    group: root
  notify: Enable pooposting
  with_items:
    - "{{ db_users }}"
- name: Wykonanie dotnet publish
  ansible.builtin.command:
    chdir: "/home/debian/pooposting-backend-{{ item.type }}/PooPosting.Api"
    cmd: "dotnet publish --configuration Release --output /var/www/pooposting-{{ item.type }}/api"
  changed_when: true
  with_items:
    - "{{ db_users }}"
  notify: Restart pooposting
- name: Podrzucenie konfiguracji nginx pooposting
  notify: Restart nginx
  block:
    - name: Podrzucenie templateów
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "/etc/nginx/sites-available/{{ item.dest }}"
        mode: 0644
        owner: root
        group: root
      with_items:
        - { src: 'nginx-poo-prod.j2', dest: 'pooposting-prod.vhost' }
        - { src: 'nginx-poo-dev.j2', dest: 'pooposting-dev.vhost' }
    - name: Uruchomienie konfiguracji nginx pooposting
      ansible.builtin.file:
        state: link
        src: "/etc/nginx/sites-available/pooposting-{{ item.type }}.vhost"
        dest: "/etc/nginx/sites-enabled/pooposting-{{ item.type }}.vhost"
      with_items:
        - "{{ db_users }}"
...
