name: Deploy Dotnet environement
run-name: ${{ github.actor }} wdraża
on: [workflow_dispatch]
concurrency:
  group: PooPosting
  cancel-in-progress: false
jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Git repo
        uses: actions/checkout@v3
      - name: Uruchomienie skryptów python
        env:
          API_KEY_DEVOPS: ${{secrets.API_KEY_DEVOPS}}
          OVH_APP_KEY: ${{secrets.OVH_APP_KEY}}
          OVH_APP_SECRET: ${{secrets.OVH_APP_SECRET}}
          OVH_CONSUMER_KEY: ${{secrets.OVH_CONSUMER_KEY}}
          aktualizowac: "owszem"
        run: |
          python -m pip install --upgrade pip
          if [ -f .github/workflows/requirements.txt ]; then
            pip install -r .github/workflows/requirements.txt; 
          fi
          python -u .github/workflows/varsManage.py
      - name: Wypełnianie plików sekretami
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: roles/wdrozenie/vars/main.yml
          substitutionRegex: \$\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(secrets) }}
      - name: Wypełnianie plików sekretami
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: roles/web_config/vars/main.yml
          substitutionRegex: \$\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(secrets) }}
      - name: Wypełnianie plików zmiennymi
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: roles/web_config/vars/main.yml
          substitutionRegex: \^\{([A-Z0-9_]+)\}
          substitutionData: ${{ toJSON(vars) }}
      - name: Zaciągnięcie pliku appsettings
        run: "wget https://raw.githubusercontent.com/PooPosting/Back-end/master/PooPosting.Api/appsettings.Template.json -O roles/web_config/templates/prod-appsettings.json"
      - name: Wypełnianie plików sekretami
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: roles/web_config/templates/prod-appsettings.json
          substitutionRegex: \$<([A-Z0-9_]+)>
          substitutionData: ${{ toJSON(secrets) }}
      - name: Zaciągnięcie pliku appsettings
        run: "wget https://raw.githubusercontent.com/PooPosting/Back-end/development/PooPosting.Api/appsettings.Template.json -O roles/web_config/templates/dev-appsettings.json"
      - name: Wypełnianie plików sekretami
        uses: faradaytrs/substitute-secrets-action@2.1
        with:
          input: roles/web_config/templates/dev-appsettings.json
          substitutionRegex: \$<([A-Z0-9_]+)>
          substitutionData: ${{ toJSON(secrets) }}
      - name: Run ansible playbook
        uses: aimerib/ansible-playwright@master
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [vps]
            ${{ secrets.IP }}